# Generated by Django 6.0.3 on 2026-04-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.URLField(blank=True),
        ),
    ]
