# Generated by Django 6.0.3 on 2026-04-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_author_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='photo',
        ),
    ]
